"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.1
"""

from pathlib import Path

# ---------------- BASE DIR ----------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------- SECURITY ----------------
SECRET_KEY = 'django-insecure-dev-key-change-in-production'
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# ---------------- APPLICATIONS ----------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local apps
    'health',
]


# ---------------- MIDDLEWARE ----------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # MUST be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ---------------- URL / WSGI ----------------
ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'


# ---------------- TEMPLATES ----------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ---------------- DATABASE ----------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------- PASSWORD VALIDATION ----------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------- INTERNATIONALIZATION ----------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------- STATIC FILES ----------------
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------- CORS CONFIG (REACT ↔ DJANGO) ----------------
CORS_ALLOW_ALL_ORIGINS = True   # DEV only


# ---------------- DRF CONFIG ----------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# ---------------- FIREBASE (OPTIONAL – SAFE MODE) ----------------
# Firebase is OPTIONAL now. Backend WILL NOT crash if key is missing.

USE_FIREBASE = True   # change to True when ready

if USE_FIREBASE:
    try:
        import firebase_admin
        from firebase_admin import credentials
        from pathlib import Path

        # FIXED PATH (use raw string + Path)
        FIREBASE_SERVICE_ACCOUNT_KEY_PATH = Path(
            r"E:\E PPSU\SEM 6\Antigravity\RISK PREDICTOR\backend\firebase-sdk.json"
        )

        if FIREBASE_SERVICE_ACCOUNT_KEY_PATH.exists():

            # Prevent duplicate initialization error
            if not firebase_admin._apps:
                cred = credentials.Certificate(str(FIREBASE_SERVICE_ACCOUNT_KEY_PATH))
                firebase_admin.initialize_app(cred, {
                    'databaseURL': 'https://risk-predictor-7d635-default-rtdb.firebaseio.com/'
                })

            print("Firebase initialized successfully")

        else:
            print("Firebase key not found, skipping Firebase init")

    except Exception as e:
        print("Firebase init failed:", e)
