# Generated by Django 6.0.1 on 2026-01-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('is_smoker', models.BooleanField(default=False)),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly Active', 'Lightly Active (exercise 1-3 days/week)'), ('Moderately Active', 'Moderately Active (exercise 3-5 days/week)'), ('Very Active', 'Very Active (exercise 6-7 days/week)')], max_length=20)),
                ('has_diabetes_history', models.BooleanField(default=False)),
                ('has_heart_history', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('parent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='health.healthprofile')),
            ],
        ),
    ]
